proxy:
  title: Tonga Crop Survey Portal
  port: 8080 # use Port 8080 for ShinyProxy
  template-path: ./templates
  hide-navbar: true
  
  container-wait-time: 60000 # how long should we wait for the container to spin up (30s as default)
  heartbeat-rate: 20000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 120000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)
  
  authentication: none
  
  # Set the container backend: The container-backend can be one of docker (default), docker-swarm or Kubernetes
  container-backend: docker-swarm
  
  docker:
      internal-networking: true
  
  # Below is a list of apps and their config
  specs:
    - id: maplandscape-view
      display-name: Tonga Crop Survey Viewer
      description: Explore Tonga Crop Survey data on web maps and generate summary reports for villages and districts.
      container-cmd: ["R", "-e", "shiny::runApp('/root/app', port = 3838, host = '0.0.0.0')"]
      container-image: 127.0.0.1:5000/maplandscape-view 
      container-network: sp-net

    - id: maplandscape
      display-name: Geospatial Data Explorer
      description: Analyse and explore geospatial data with interactive tables, web maps, and custom charts.
      container-cmd: ["R", "-e", "shiny::runApp('/root/app', port = 3838, host = '0.0.0.0')"]
      container-image: 127.0.0.1:5000/maplandscape 
      container-network: sp-net

server:
  useForwardHeaders: true # this is very important to make the AWS Cognito auth works

logging:
  file:
    shinyproxy.log